# Generated by Django 4.1.2 on 2022-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="ID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pwd", models.CharField(db_column="PWD", max_length=100)),
                ("regdate", models.DateTimeField(db_column="REGDATE")),
                ("name", models.CharField(db_column="NAME", max_length=100)),
            ],
            options={"db_table": "users", "managed": False,},
        ),
    ]
