# Generated by Django 4.1.2 on 2022-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("pwd", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("regdate", models.DateTimeField()),
            ],
            options={"db_table": "wine_user", "managed": False,},
        ),
        migrations.DeleteModel(name="Users",),
    ]
